### ISSUE TITLE
Pesky 'node_helpers'

### ISSUE THREAD

**Issue by RONNYKHALIL** [audioscavenger/ComfyUI-Thumbnails#2]
I love love love this humble lil custom node. I can't stress enough how useful something like this is for my comfy experiments...

I see the lovely thumbnails. However running it inside any kind of a workflow, I receive this error:

```
Error occurred when executing LoadImage:

name 'node_helpers' is not defined

File "/workspace/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/workspace/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/workspace/ComfyUI/custom_nodes/ComfyUI-Thumbnails/ComfyUIThumbnails.py", line 109, in load_image
img = node_helpers.pillow(Image.open, image_path)
```

Got the same error on 3 different comfy setups (local on M1, Runpod, and Paperspace)

Any help would be more than appreciated

**Comment by var1ableX** [comment]
@RONNYKHALIL / @audioscavenger I've fixed the issue in my fork. I'm not a python / comfyui dev by any means and am doubtful I'll be able to maintain this node long term. Hopefully audioscavenger can incorporate the changes -- essentially the node_helpers module is missing and needs to be readded - in the meantime I've done a quick and dirty patch to remove dependency on this module.

**Comment by RONNYKHALIL** [comment]
oh hell yea! much appreciated!!! works great

**Comment by var1ableX** [comment]
> oh hell yea! much appreciated!!! works great
@RONNYKHALIL 
actually I'm running into some problems I'm trying to fix:
1. Even if I don't change the image hitting queue rerenders
2. The node seems to override the stock node that comes with Comfy (even though the original code seems to try and avoid this)
3. if you disable the node in ComfyManager Menu (the gear icon) then right click menu stops working.

**Comment by var1ableX** [comment]
@RONNYKHALIL - I've updated the node, it should fix the first issue with comfy rerendering even if you don't change the source image. HOWEVER, I seem to have broken the delete function and it's a bit too complicated for me to figure this out quickly. It's easy enough for me to delete images from the comfyui/inputs folder anyway.

@audioscavenger - amazing work on this, I've really struggled to find anything like it and I think it's very useful. I ended up commenting out almost everything in ComfyUIThumbnails.py except for the deleteImage function. I changed __init__.py to reference NODE_CLASS_MAPPINGS etc directly from nodes. I assumed this would work b/c you're intercepting events from the stock node in your javascript anyway. It worked, but unfortunately this broke delete. The delete event is detected, but I get an error related to bad json...

Perhaps if you get the time you might be able to figure this out quickly, but otherwise I can work with this.

Would also be a bonus if you could fix pt 3 - but again not a big deal at the moment.

Thanks again.

**Comment by RONNYKHALIL** [comment]
Thanks @var1ableX and @audioscavenger. this is so essential for my cloud based setups.

**Comment by audioscavenger** [comment]
YES I CAN incorporate your changes. no promises but I will look at this today.
the house move exhausted me, because I also had to fix the pool and paint and mud and fix electric outlets and to top it all my AC blew up last Friday, it's 89 upstairs and I can't sleep and code and the main PC is still wrapped... though times but hopefully after the AC is fixed I can start arganizing the house and unwrap the computer with Comfy in it.
Sorry about the personal rambling, s...t just happens sometimes.

and thank you for finding the bug. If I @var1ableX wants to be added as a maintainer let me know !!

**Comment by audioscavenger** [comment]
> Thanks @var1ableX and @audioscavenger. this is so essential for my cloud based setups.

you are welcome! I felt like this was essential for me too, especially the removing duplicate part, as everytime to add the same pic it's duplicated and the list gets too long and boring. Glad it helps you!

**Comment by var1ableX** [comment]
> YES I CAN incorporate your changes. no promises but I will look at this today. the house move exhausted me, because I also had to fix the pool and paint and mud and fix electric outlets and to top it all my AC blew up last Friday, it's 89 upstairs and I can't sleep and code and the main PC is still wrapped... though times but hopefully after the AC is fixed I can start arganizing the house and unwrap the computer with Comfy in it. Sorry about the personal rambling, s...t just happens sometimes.
> 
> and thank you for finding the bug. If I @var1ableX wants to be added as a maintainer let me know !!

Take your time, sounds like there's a lot going on (good luck with the AC - crazy hot and humid right now so I hope it gets resolved quickly). I'll let your know re maintainer - not sure I'm strong enough on python and comfy in general esp. the web / extension stuff. It took some guesswork and luck to comment everything out in the main file and still get things to work. But will keep an eye on the repo and send you pull requests if I think I can fix anything. We can go from there to maintainer if I'm adding value.

**Comment by alexbofa** [comment]
yes, the same error

**Comment by audioscavenger** [comment]
who wants to maintain it? I'll make you guys collaborators, how does that sound?
i am force to work extra as Bidenomics work so well for me, I am ruined. No time for this project anymore.

**Comment by Piscabo** [comment]
> who wants to maintain it? I'll make you guys collaborators, how does that sound? i am force to work extra as Bidenomics work so well for me, I am ruined. No time for this project anymore.

And everyone ran for the hills. I wish I knew how... I would still love to see this work. PLS.

**Comment by var1ableX** [comment]
Unfortunately I cannot right now as I’m heads down on a couple of projects and struggling to find time on these two already. What I discovered was my flow now depends on Pinterest and basically I use Pinterest to find and drag images directly into the Load Image node. So Pinterest is my thumbnails. Or I can use explorer. The only issue is the input folder size but I can always delete everything in there. All that said, I haven’t used comfy in 2 weeks now given the workload on the other projects! What is bidenomics?On Nov 15, 2024, at 8:00 AM, Piscabo ***@***.***> wrote:﻿

who wants to maintain it? I'll make you guys collaborators, how does that sound? i am force to work extra as Bidenomics work so well for me, I am ruined. No time for this project anymore.

And everyone ran for the hills. I wish I knew how... I would still love to see this work. PLS.

**Comment by audioscavenger** [comment]
Okay I mostly fixed the UI side of it because of the switch to TS: must use root from context as "this" is now undefined and also 'event' seem deprecated. JS is hard to keep up with, whatever you do today seems to break is less then a year.
Anyhow, I agree node_helpers.pillow is the problem, but how do I replace that?
